version: 2.1

orbs:
  swissknife: roopakv/swissknife@0.24.0

workflows:
  rimg-packer-ci:
    jobs:
      - build-and-push:
          context: docker-publishing

jobs:
  build-and-push:
    docker:
      - image: cibuilds/docker:19.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build Image"
          command: ./build-image.sh
      - swissknife/run_on_branch:
          branch-pattern: "master"
          steps-to-run:
            - deploy:
                name: Push image to docker
                command: |
                  echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin

                  if git log -1 --pretty=%s | grep "\[release\]"; then
                    echo "Pushing to dockerhub"
                    docker push roopakv/rimg-packer
                  else
                    echo "Skip publishing."
                  fi